const products = [
    {
      id: 1,
      name: "Laptop",
      description: "A powerful laptop for work and play.",
      price: 999.99,
      quantity: 10,
      image: "./assets/productHmgs/laptop.jpg",
      category: "Electronics",
      brand: "Acer",
      features: ["Intel Core i7", "16GB RAM", "1TB SSD"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 2,
      name: "Smartphone",
      description: "A high-end smartphone with a stunning display.",
      price: 799.99,
      quantity: 20,
      image: "./assets/productHmgs/smartphone.jpg",
      category: "Electronics",
      brand: "Samsung",
      features: ["6.5-inch AMOLED screen", "12GB RAM", "128GB storage"],
      dicount: true,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: true
    },
    {
      id: 3,
      name: "Headphones",
      description: "Wireless headphones with excellent sound quality.",
      price: 149.99,
      quantity: 50,
      image: "./assets/productHmgs/headphones.jpg",
      category: "Electronics",
      brand: "Sony",
      features: ["Active noise cancellation", "Up to 30 hours battery life"],
      dicount: true,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 4,
      name: "Smartwatch",
      description: "A stylish smartwatch with fitness tracking features.",
      price: 299.99,
      quantity: 30,
      image: "./assets/productHmgs/smartwatch.jpg",
      category: "Wearables",
      brand: "Apple",
      features: ["Heart rate monitor", "GPS", "Apple Pay"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: true
    },
    {
      id: 5,
      name: "Gaming Console",
      description: "A powerful gaming console for immersive gaming experiences.",
      price: 499.99,
      quantity: 15,
      image: "./assets/productHmgs/gaming-console.jpg",
      category: "Electronics",
      brand: "PlayStation",
      features: ["4K gaming", "DualSense controller", "PlayStation Plus"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 6,
      name: "Tablet",
      description: "A versatile tablet for work, play, and entertainment.",
      price: 399.99,
      quantity: 25,
      image: "./assets/productHmgs/tablet.jpg",
      category: "Electronics",
      brand: "iPad",
      features: ["10.9-inch Liquid Retina display", "A13 Bionic chip", "Apple Pencil support"],
      dicount: true,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: true
    },
    {
      id: 7,
      name: "Camera",
      description: "A high-quality camera for capturing stunning photos and videos.",
      price: 799.99,
      quantity: 10,
      image: "./assets/productHmgs/camera.jpg",
      category: "Photography",
      brand: "Canon",
      features: ["Full-frame sensor", "4K video recording", "5-axis image stabilization"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: true,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 8,
      name: "Bluetooth Speaker",
      description: "A portable Bluetooth speaker with powerful sound.",
      price: 99.99,
      quantity: 100,
      image: "./assets/productHmgs/bluetooth-speaker.jpg",
      category: "Audio",
      brand: "JBL",
      features: ["Waterproof design", "Up to 12 hours battery life"],
      dicount: true,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: true
    },
    {
      id: 9,
      name: "Drone",
      description: "A fun and versatile drone for aerial photography and videography.",
      price: 499.99,
      quantity: 20,
      image: "./assets/productHmgs/drone.jpg",
      category: "Gadgets",
      brand: "DJI",
      features: ["4K camera", "Obstacle avoidance", "Up to 30 minutes flight time"],
      dicount: true,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 10,
      name: "Fitness Tracker",
      description: "A stylish fitness tracker with advanced features.",
      price: 199.99,
      quantity: 40,
      image: "./assets/productHmgs/fitness-tracker.jpg",
      category: "Wearables",
      brand: "Fitbit",
      features: ["Heart rate monitor", "Sleep tracking", "GPS"],
      dicount: true,
      specialOffer: "Buy two get extra one for free",
      offer: true,
      discountRercent: 10,
      bestSeller: true
    },
    {
      id: 11,
      name: "Gaming Headset",
      description: "A comfortable gaming headset with immersive sound.",
      price: 99.99,
      quantity: 50,
      image: "./assets/productHmgs/gaming-headset.jpg",
      category: "Gaming",
      brand: "Razer",
      features: ["7.1 surround sound", "Noise-canceling microphone"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 12,
      name: "Smart Home Hub",
      description: "A central hub for controlling your smart home devices.",
      price: 149.99,
      quantity: 30,
      image: "./assets/productHmgs/smart-home-hub.jpg",
      category: "Home",
      brand: "Amazon",
      features: ["Voice control", "Integration with various smart devices"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: true
    },
    {
      id: 13,
      name: "Portable Charger",
      description: "A powerful portable charger for keeping your devices powered on the go.",
      price: 39.99,
      quantity: 100,
      image: "./assets/productHmgs/portable-charger.jpg",
      category: "Accessories",
      brand: "Anker",
      features: ["Fast charging", "Multiple USB ports"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: true,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 14,
      name: "Wireless Earbuds",
      description: "Compact and wireless earbuds with great sound quality.",
      price: 79.99,
      quantity: 80,
      image: "./assets/productHmgs/wireless-earbuds.jpg",
      category: "Audio",
      brand: "Apple",
      features: ["Noise cancellation", "Siri integration"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 15,
      name: "Action Camera",
      description: "A rugged action camera for capturing adventures.",
      price: 299.99,
      quantity: 20,
      image: "./assets/productHmgs/action-camera.jpg",
      category: "Photography",
      brand: "GoPro",
      features: ["4K video recording", "Waterproof", "Image stabilization"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 16,
      name: "Smart Speaker",
      description: "A voice-controlled smart speaker for music, information, and home control.",
      price: 99.99,
      quantity: 60,
      image: "./assets/productHmgs/smart-speaker.jpg",
      category: "Home",
      brand: "Google",
      features: ["Google Assistant", "Music streaming", "Smart home integration"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: true,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 17,
      name: "Gaming Mouse",
      description: "A high-precision gaming mouse with customizable settings.",
      price: 49.99,
      quantity: 70,
      image: "./assets/productHmgs/gaming-mouse.jpg",
      category: "Gaming",
      brand: "Logitech",
      features: ["RGB lighting", "Adjustable DPI", "Programmable buttons"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
    {
      id: 18,
      name: "Projector",
      description: "A powerful projector for creating immersive home theater experiences.",
      price: 499.99,
      quantity: 15,
      image: "./assets/productHmgs/projector.jpg",
      category: "Home Entertainment",
      brand: "BenQ",
      features: ["Full HD resolution", "High brightness", "Built-in speakers"],
      dicount: false,
      specialOffer: "Buy two get extra one for free",
      offer: false,
      discountRercent: 10,
      bestSeller: false
    },
      {
        id: 19,
        name: "Robot Vacuum",
        description: "A smart robot vacuum that cleans your floors automatically.",
        price: 299.99,
        quantity: 25,
        image: "./assets/productHmgs/robot-vacuum.jpg",
        category: "Home Appliances",
        brand: "iRobot",
        features: ["Voice control", "Mapping technology", "Smart scheduling"],
        dicount: false,
        specialOffer: "Buy two get extra one for free",
        offer: false,
        discountRercent: 10,
        bestSeller: false
      },
      {
        id: 20,
        name: "VR Headset",
        description: "A virtual reality headset for immersive gaming and entertainment.",
        price: 399.99,
        quantity: 10,
        image: "./assets/productHmgs/vr-headset.jpg",
        category: "Gaming",
        brand: "Oculus",
        features: ["High-resolution display", "Motion tracking", "Wireless connectivity"],
        dicount: false,
        specialOffer: "Buy two get extra one for free",
        offer: true,
        discountRercent: 10,
        bestSeller: false
      },
      {
        id: 21,
        name: "VR Headset",
        description: "A high copy virtual reality headset for immersive gaming.",
        price: 100.99,
        quantity: 8,
        image: "./assets/productHmgs/vr-headset.jpg",
        category: "Gaming",
        brand: "Oculus",
        features: ["High-resolution display", "Motion tracking", "Wireless connectivity"],
        dicount: true,
        specialOffer: "Buy two get extra one for free",
        offer: true,
        discountRercent: 10,
        bestSeller: false
      }
  ];

  export default products;